# Generated by Django 5.0.4 on 2024-04-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
