# Generated by Django 5.0.4 on 2024-04-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=100),
        ),
    ]
