services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: digi
      POSTGRES_PASSWORD: digi
      POSTGRES_DB: quotedb
    networks:
      - app-network

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      POSTGRES_DB: quotedb
      POSTGRES_USER: digi
      POSTGRES_PASSWORD: digi
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000  # Use localhost for browser access
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: